package config

import (
	"os"
	"path/filepath"
	"strings"
	"time"
)

const installMetaFile = "crosspile-install-meta.toml"

type InstallMeta struct {
	RepoDir       string
	Origin        string
	CurrentCommit string
	InstalledAt   string
	InstallSource string
	Platform      string
}

func WriteInstallMeta(repoDir, origin, currentCommit, installSource, platform string) error {
	dir, err := ConfigDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	meta := InstallMeta{
		RepoDir:       repoDir,
		Origin:        origin,
		CurrentCommit: currentCommit,
		InstalledAt:   time.Now().UTC().Format(time.RFC3339),
		InstallSource: installSource,
		Platform:      platform,
	}
	content := "# Auto-generated by the crosspile installer. Do not edit manually.\n" +
		`repo_dir = "` + escapeTomlString(meta.RepoDir) + `"` + "\n" +
		`origin = "` + escapeTomlString(meta.Origin) + `"` + "\n" +
		`current_commit = "` + escapeTomlString(meta.CurrentCommit) + `"` + "\n" +
		`installed_at = "` + escapeTomlString(meta.InstalledAt) + `"` + "\n" +
		`install_source = "` + escapeTomlString(meta.InstallSource) + `"` + "\n" +
		`platform = "` + escapeTomlString(meta.Platform) + `"` + "\n"
	return os.WriteFile(filepath.Join(dir, installMetaFile), []byte(content), 0o644)
}

func ReadInstallMeta() InstallMeta {
	dir, err := ConfigDir()
	if err != nil {
		return InstallMeta{}
	}
	data, err := os.ReadFile(filepath.Join(dir, installMetaFile))
	if err != nil {
		return InstallMeta{}
	}
	meta := InstallMeta{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		value = unescapeTomlString(value)
		switch strings.TrimSpace(key) {
		case "repo_dir":
			meta.RepoDir = value
		case "origin":
			meta.Origin = value
		case "current_commit":
			meta.CurrentCommit = value
		case "installed_at":
			meta.InstalledAt = value
		case "install_source":
			meta.InstallSource = value
		case "platform":
			meta.Platform = value
		}
	}
	return meta
}

func escapeTomlString(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	return value
}

func unescapeTomlString(value string) string {
	value = strings.TrimSpace(value)
	value = strings.Trim(value, `"`)
	value = strings.ReplaceAll(value, `\"`, `"`)
	value = strings.ReplaceAll(value, `\\`, `\`)
	return value
}
